# Generated by Django 3.2 on 2021-06-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descr',
            new_name='description',
        ),
    ]
